name: test project
on: push
jobs:
  autoactions: 
    runs-on: ubuntu-latest
    steps:
     - name: getcode
       uses: actions/checkout@v3
     - name: install node
       uses: actions/setup-node@v3
       with:
        node-version: 18
     - name: install dependencies
       run: npm ci
     - name: run tests
       run: npm test
  deploy:
   runs-0n:
    steps:
     - name: getcode
       uses: actions/checkout@v3
     - name: install node
       uses: actions/setup-node@v3
       with:
        node-version: 18
     - name: install dependencies
       run: npm ci
     - name: run tests
       run: npm test
     - name: build
       run: npm test build
     - name: deploy
       run: echo" deployed"
       
        


   
   